dataset:
    name: svhn

regressor:
    source: result/source/svhn/source_model_114500.pt
    type: image
    config:
        backbone: resnet26
        pretrained: false
        in_channels: 3

calculator:
    compile_model: null

dataloader:
    batch_size: 256
