dataset:
  name: biwi_kinect
  config:
    gender: male
    target: pitch
  train_ratio: 0.0

regressor:
  source: result/source/biwi_kinect/female_pitch/source_model_7400.pt
  type: image
  config:
    backbone: resnet50
    pretrained: false
    in_channels: 3

optimizer:
  name: Adam
  param: fe_bn
  config:
    lr: 0.001
    weight_decay: 0.0

tta:
  type: pca
  train_mode: true
  weight_bias: 1.0
  weight_exp: 1.0
  pc_config:
    stat_file: result/source/biwi_kinect/female_pitch/feature_stats.pt
    contrib_top_k: 100
  loss_config:
    eps: 1.0e-8
  compile_model: &compile_model null

evaluator:
  compile_model: *compile_model

adapt_dataloader:
  batch_size: 64
  shuffle: true

val_dataloader:
  batch_size: 256
