dataset:
  name: utkface
  config:
    filter_gender: null
  val_indices: configs/utkface-all_val_indices.npy
  val_corruption:
    corruption_type: gaussian_noise
    severity: 5

regressor:
  source: result/source/utkface/source_model_29700.pt
  type: image
  config:
    backbone: resnet50
    pretrained: false
    in_channels: 3

optimizer:
  param: fe_bn
  name: Adam
  config:
    lr: 0.001
    weight_decay: 0.0

tta:
  config:
    train_mode: true
    weight_bias: 1.0
    weight_exp: 1.0
    pc_config:
      stat_file: result/source/utkface_all/feature_stats.pt
      contrib_top_k: 100
    loss_config:
      eps: 1.0e-8
    compile_model: &compile_model null

evaluator:
  compile_model: *compile_model

adapt_dataloader:
  batch_size: 64
  shuffle: true

val_dataloader:
  batch_size: 256
